# ===== Build Stage =====
FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app

# copy pom.xml and download dependencies (cache layer)
COPY pom.xml .
RUN mvn dependency:go-offline -B

# copy source code
COPY src ./src

# build jar
RUN mvn clean package -DskipTests

# ===== Run Stage =====
FROM eclipse-temurin:17-jdk

WORKDIR /app

# copy jar from the build stage
COPY --from=build /app/target/*.jar app.jar

# expose port (Render auto-detects)
EXPOSE 9090

# run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
